// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.drools.builder;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class KnowledgeBuilder_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return org.drools.builder.KnowledgeBuilder_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        org.drools.builder.KnowledgeBuilder_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __KnowledgeBuilder extends system.Object implements org.drools.builder.KnowledgeBuilder {
    
    protected __KnowledgeBuilder(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/io/Resource;Lorg/drools/builder/ResourceType;Lorg/drools/builder/ResourceConfiguration;)V")
    public native void add(org.drools.io.Resource par0, org.drools.builder.ResourceType par1, org.drools.builder.ResourceConfiguration par2);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/io/Resource;Lorg/drools/builder/ResourceType;)V")
    public native void add(org.drools.io.Resource par0, org.drools.builder.ResourceType par1);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Collection;")
    public native java.util.Collection getKnowledgePackages();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lorg/drools/KnowledgeBase;")
    public native org.drools.KnowledgeBase newKnowledgeBase();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean hasErrors();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lorg/drools/builder/KnowledgeBuilderErrors;")
    public native org.drools.builder.KnowledgeBuilderErrors getErrors();
}
//</generated-proxy>
