// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system;

@net.sf.jni4net.attributes.ClrInterface
public interface IComparable {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)I")
    int CompareTo(system.Object obj);
    //</generated-interface>
}
