//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:2.0.50727.3074
//
//     Zmìny tohoto souboru mohou zpùsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace net.sf.jni4net.proxygen.config
{
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://jni4net.sf.net/0.2.0.0/toolConfig.xsd")]
    [XmlRoot("jni4net-proxygen", Namespace = "http://jni4net.sf.net/0.2.0.0/toolConfig.xsd", IsNullable = false)]
    public partial class ToolConfig
    {
        private string[] assemblyReferenceField;
        private string[] classPathField;

        private TypeRegistration[] clrTypeField;
        private TypeRegistration[] javaClassField;
        private bool skipInterfaceTypeInfoField;
        private bool skipSignaturesField;
        private string targetDirClrField;
        private string targetDirJvmField;
        private bool verboseField;

        public ToolConfig()
        {
            skipSignaturesField = false;
            skipInterfaceTypeInfoField = false;
            verboseField = false;
        }

        /// <remarks/>
        public string TargetDirJvm
        {
            get { return targetDirJvmField; }
            set { targetDirJvmField = value; }
        }

        /// <remarks/>
        public string TargetDirClr
        {
            get { return targetDirClrField; }
            set { targetDirClrField = value; }
        }

        /// <remarks/>
        [DefaultValue(false)]
        public bool SkipSignatures
        {
            get { return skipSignaturesField; }
            set { skipSignaturesField = value; }
        }

        /// <remarks/>
        [DefaultValue(false)]
        public bool SkipInterfaceTypeInfo
        {
            get { return skipInterfaceTypeInfoField; }
            set { skipInterfaceTypeInfoField = value; }
        }

        /// <remarks/>
        [XmlElement("ClassPath")]
        public string[] ClassPath
        {
            get { return classPathField; }
            set { classPathField = value; }
        }

        /// <remarks/>
        [XmlElement("AssemblyReference")]
        public string[] AssemblyReference
        {
            get { return assemblyReferenceField; }
            set { assemblyReferenceField = value; }
        }

        /// <remarks/>
        [DefaultValue(false)]
        public bool Verbose
        {
            get { return verboseField; }
            set { verboseField = value; }
        }

        /// <remarks/>
        [XmlElement("JavaClass")]
        public TypeRegistration[] JavaClass
        {
            get { return javaClassField; }
            set { javaClassField = value; }
        }

        /// <remarks/>
        [XmlElement("ClrType")]
        public TypeRegistration[] ClrType
        {
            get { return clrTypeField; }
            set { clrTypeField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://jni4net.sf.net/0.2.0.0/toolConfig.xsd")]
    public partial class TypeRegistration
    {
        private TypeReference[] ignoreInterfaceField;
        private bool mergeJavaSourceField;

        private MethodModifier[] methodModifierField;

        private bool noMethodsField;

        private bool syncInterfaceField;
        private string typeNameField;

        public TypeRegistration()
        {
            noMethodsField = false;
            syncInterfaceField = false;
            mergeJavaSourceField = false;
        }

        /// <remarks/>
        [XmlElement("IgnoreInterface")]
        public TypeReference[] IgnoreInterface
        {
            get { return ignoreInterfaceField; }
            set { ignoreInterfaceField = value; }
        }

        /// <remarks/>
        [XmlElement("MethodModifier")]
        public MethodModifier[] MethodModifier
        {
            get { return methodModifierField; }
            set { methodModifierField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string TypeName
        {
            get { return typeNameField; }
            set { typeNameField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(false)]
        public bool NoMethods
        {
            get { return noMethodsField; }
            set { noMethodsField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(false)]
        public bool SyncInterface
        {
            get { return syncInterfaceField; }
            set { syncInterfaceField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(false)]
        public bool MergeJavaSource
        {
            get { return mergeJavaSourceField; }
            set { mergeJavaSourceField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://jni4net.sf.net/0.2.0.0/toolConfig.xsd")]
    public partial class TypeReference
    {
        private string typeNameField;

        /// <remarks/>
        [XmlAttribute()]
        public string TypeName
        {
            get { return typeNameField; }
            set { typeNameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://jni4net.sf.net/0.2.0.0/toolConfig.xsd")]
    public partial class MethodModifier
    {
        private bool forceField;

        private string interfaceField;
        private string methodNameField;

        private string renameCLRField;
        private string renameJVMField;
        private string returnField;
        private string signatureField;

        private bool skipField;

        public MethodModifier()
        {
            skipField = false;
            forceField = false;
        }

        /// <remarks/>
        [XmlAttribute()]
        public string MethodName
        {
            get { return methodNameField; }
            set { methodNameField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Signature
        {
            get { return signatureField; }
            set { signatureField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(false)]
        public bool Skip
        {
            get { return skipField; }
            set { skipField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(false)]
        public bool Force
        {
            get { return forceField; }
            set { forceField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Return
        {
            get { return returnField; }
            set { returnField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Interface
        {
            get { return interfaceField; }
            set { interfaceField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string RenameJVM
        {
            get { return renameJVMField; }
            set { renameJVMField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string RenameCLR
        {
            get { return renameCLRField; }
            set { renameCLRField = value; }
        }
    }
}