// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.collections;

@net.sf.jni4net.attributes.ClrInterface
public interface IList extends system.collections.ICollection, system.collections.IEnumerable {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(I)LSystem/Object;")
    system.Object getItem(int index);
    
    @net.sf.jni4net.attributes.ClrMethod("(ILSystem/Object;)V")
    void setItem(int index, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)I")
    int Add(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)Z")
    boolean Contains(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void Clear();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean isReadOnly();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean isFixedSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)I")
    int IndexOf(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(ILSystem/Object;)V")
    void Insert(int index, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)V")
    void Remove(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    void RemoveAt(int index);
    //</generated-interface>
}
