//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.agent {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface KnowledgeAgentConfiguration : global::org.drools.PropertiesConfiguration {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        bool isScanResources();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        bool isScanDirectories();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        bool isMonitorChangeSetEvents();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        bool isNewInstance();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        bool isUseKBaseClassLoaderForCompiling();
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class KnowledgeAgentConfiguration_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::org.drools.agent.KnowledgeAgentConfiguration), typeof(global::org.drools.agent.KnowledgeAgentConfiguration_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::org.drools.agent.KnowledgeAgentConfiguration), typeof(global::org.drools.agent.KnowledgeAgentConfiguration_))]
    internal sealed partial class @__KnowledgeAgentConfiguration : global::java.lang.Object, global::org.drools.agent.KnowledgeAgentConfiguration {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _setProperty0;
        
        internal static global::net.sf.jni4net.jni.MethodId _getProperty1;
        
        internal static global::net.sf.jni4net.jni.MethodId _isScanResources2;
        
        internal static global::net.sf.jni4net.jni.MethodId _isScanDirectories3;
        
        internal static global::net.sf.jni4net.jni.MethodId _isMonitorChangeSetEvents4;
        
        internal static global::net.sf.jni4net.jni.MethodId _isNewInstance5;
        
        internal static global::net.sf.jni4net.jni.MethodId _isUseKBaseClassLoaderForCompiling6;
        
        private @__KnowledgeAgentConfiguration(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass = @__class;
            global::org.drools.agent.@__KnowledgeAgentConfiguration._setProperty0 = @__env.GetMethodID(global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass, "setProperty", "(Ljava/lang/String;Ljava/lang/String;)V");
            global::org.drools.agent.@__KnowledgeAgentConfiguration._getProperty1 = @__env.GetMethodID(global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass, "getProperty", "(Ljava/lang/String;)Ljava/lang/String;");
            global::org.drools.agent.@__KnowledgeAgentConfiguration._isScanResources2 = @__env.GetMethodID(global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass, "isScanResources", "()Z");
            global::org.drools.agent.@__KnowledgeAgentConfiguration._isScanDirectories3 = @__env.GetMethodID(global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass, "isScanDirectories", "()Z");
            global::org.drools.agent.@__KnowledgeAgentConfiguration._isMonitorChangeSetEvents4 = @__env.GetMethodID(global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass, "isMonitorChangeSetEvents", "()Z");
            global::org.drools.agent.@__KnowledgeAgentConfiguration._isNewInstance5 = @__env.GetMethodID(global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass, "isNewInstance", "()Z");
            global::org.drools.agent.@__KnowledgeAgentConfiguration._isUseKBaseClassLoaderForCompiling6 = @__env.GetMethodID(global::org.drools.agent.@__KnowledgeAgentConfiguration.staticClass, "isUseKBaseClassLoaderForCompiling", "()Z");
        }
        
        public void setProperty(global::java.lang.String par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::org.drools.agent.@__KnowledgeAgentConfiguration._setProperty0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1));
            }
        }
        
        public global::java.lang.String getProperty(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.agent.@__KnowledgeAgentConfiguration._getProperty1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public bool isScanResources() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::org.drools.agent.@__KnowledgeAgentConfiguration._isScanResources2)));
            }
        }
        
        public bool isScanDirectories() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::org.drools.agent.@__KnowledgeAgentConfiguration._isScanDirectories3)));
            }
        }
        
        public bool isMonitorChangeSetEvents() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::org.drools.agent.@__KnowledgeAgentConfiguration._isMonitorChangeSetEvents4)));
            }
        }
        
        public bool isNewInstance() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::org.drools.agent.@__KnowledgeAgentConfiguration._isNewInstance5)));
            }
        }
        
        public bool isUseKBaseClassLoaderForCompiling() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::org.drools.agent.@__KnowledgeAgentConfiguration._isUseKBaseClassLoaderForCompiling6)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__KnowledgeAgentConfiguration);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setProperty", "setProperty0", "(Ljava/lang/String;Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getProperty", "getProperty1", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isScanResources", "isScanResources2", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isScanDirectories", "isScanDirectories3", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isMonitorChangeSetEvents", "isMonitorChangeSetEvents4", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isNewInstance", "isNewInstance5", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isUseKBaseClassLoaderForCompiling", "isUseKBaseClassLoaderForCompiling6", "()Z"));
            return methods;
        }
        
        private static void setProperty0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Ljava/lang/String;Ljava/lang/String;)V
            // (Ljava/lang/String;Ljava/lang/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.agent.KnowledgeAgentConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.agent.KnowledgeAgentConfiguration>(@__env, @__obj);
            ((global::org.drools.PropertiesConfiguration)(@__real)).setProperty(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par1));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getProperty1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (Ljava/lang/String;)Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.agent.KnowledgeAgentConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.agent.KnowledgeAgentConfiguration>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(((global::org.drools.PropertiesConfiguration)(@__real)).getProperty(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool isScanResources2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::org.drools.agent.KnowledgeAgentConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.agent.KnowledgeAgentConfiguration>(@__env, @__obj);
            @__return = ((bool)(@__real.isScanResources()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool isScanDirectories3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::org.drools.agent.KnowledgeAgentConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.agent.KnowledgeAgentConfiguration>(@__env, @__obj);
            @__return = ((bool)(@__real.isScanDirectories()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool isMonitorChangeSetEvents4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::org.drools.agent.KnowledgeAgentConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.agent.KnowledgeAgentConfiguration>(@__env, @__obj);
            @__return = ((bool)(@__real.isMonitorChangeSetEvents()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool isNewInstance5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::org.drools.agent.KnowledgeAgentConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.agent.KnowledgeAgentConfiguration>(@__env, @__obj);
            @__return = ((bool)(@__real.isNewInstance()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool isUseKBaseClassLoaderForCompiling6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::org.drools.agent.KnowledgeAgentConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.agent.KnowledgeAgentConfiguration>(@__env, @__obj);
            @__return = ((bool)(@__real.isUseKBaseClassLoaderForCompiling()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.agent.@__KnowledgeAgentConfiguration(@__env);
            }
        }
    }
    #endregion
}
