//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.runtime.rule {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface Agenda {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        void clear();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lorg/drools/runtime/rule/AgendaGroup;")]
        global::org.drools.runtime.rule.AgendaGroup getAgendaGroup(global::java.lang.String par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lorg/drools/runtime/rule/ActivationGroup;")]
        global::org.drools.runtime.rule.ActivationGroup getActivationGroup(global::java.lang.String par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lorg/drools/runtime/rule/RuleFlowGroup;")]
        global::org.drools.runtime.rule.RuleFlowGroup getRuleFlowGroup(global::java.lang.String par0);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class Agenda_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.runtime.rule.@__Agenda.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::org.drools.runtime.rule.Agenda), typeof(global::org.drools.runtime.rule.Agenda_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::org.drools.runtime.rule.Agenda), typeof(global::org.drools.runtime.rule.Agenda_))]
    internal sealed partial class @__Agenda : global::java.lang.Object, global::org.drools.runtime.rule.Agenda {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _clear0;
        
        internal static global::net.sf.jni4net.jni.MethodId _getAgendaGroup1;
        
        internal static global::net.sf.jni4net.jni.MethodId _getActivationGroup2;
        
        internal static global::net.sf.jni4net.jni.MethodId _getRuleFlowGroup3;
        
        private @__Agenda(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.runtime.rule.@__Agenda.staticClass = @__class;
            global::org.drools.runtime.rule.@__Agenda._clear0 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Agenda.staticClass, "clear", "()V");
            global::org.drools.runtime.rule.@__Agenda._getAgendaGroup1 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Agenda.staticClass, "getAgendaGroup", "(Ljava/lang/String;)Lorg/drools/runtime/rule/AgendaGroup;");
            global::org.drools.runtime.rule.@__Agenda._getActivationGroup2 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Agenda.staticClass, "getActivationGroup", "(Ljava/lang/String;)Lorg/drools/runtime/rule/ActivationGroup;");
            global::org.drools.runtime.rule.@__Agenda._getRuleFlowGroup3 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Agenda.staticClass, "getRuleFlowGroup", "(Ljava/lang/String;)Lorg/drools/runtime/rule/RuleFlowGroup;");
        }
        
        public void clear() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::org.drools.runtime.rule.@__Agenda._clear0);
            }
        }
        
        public global::org.drools.runtime.rule.AgendaGroup getAgendaGroup(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.AgendaGroup>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Agenda._getAgendaGroup1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public global::org.drools.runtime.rule.ActivationGroup getActivationGroup(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.ActivationGroup>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Agenda._getActivationGroup2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public global::org.drools.runtime.rule.RuleFlowGroup getRuleFlowGroup(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.RuleFlowGroup>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Agenda._getRuleFlowGroup3, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Agenda);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "clear", "clear0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAgendaGroup", "getAgendaGroup1", "(Ljava/lang/String;)Lorg/drools/runtime/rule/AgendaGroup;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getActivationGroup", "getActivationGroup2", "(Ljava/lang/String;)Lorg/drools/runtime/rule/ActivationGroup;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getRuleFlowGroup", "getRuleFlowGroup3", "(Ljava/lang/String;)Lorg/drools/runtime/rule/RuleFlowGroup;"));
            return methods;
        }
        
        private static void clear0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.runtime.rule.Agenda @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Agenda>(@__env, @__obj);
            @__real.clear();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getAgendaGroup1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/AgendaGroup;
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/AgendaGroup;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Agenda @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Agenda>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.AgendaGroup>(@__env, @__real.getAgendaGroup(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getActivationGroup2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/ActivationGroup;
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/ActivationGroup;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Agenda @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Agenda>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.ActivationGroup>(@__env, @__real.getActivationGroup(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getRuleFlowGroup3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/RuleFlowGroup;
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/RuleFlowGroup;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Agenda @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Agenda>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.RuleFlowGroup>(@__env, @__real.getRuleFlowGroup(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.runtime.rule.@__Agenda(@__env);
            }
        }
    }
    #endregion
}
