//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.runtime.rule {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface WorkingMemory : global::org.drools.runtime.rule.WorkingMemoryEntryPoint {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        void halt();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/runtime/rule/Agenda;")]
        global::org.drools.runtime.rule.Agenda getAgenda();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lorg/drools/runtime/rule/WorkingMemoryEntryPoint;")]
        global::org.drools.runtime.rule.WorkingMemoryEntryPoint getWorkingMemoryEntryPoint(global::java.lang.String par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/Collection;")]
        global::java.util.Collection getWorkingMemoryEntryPoints();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;[Ljava/lang/Object;)Lorg/drools/runtime/rule/QueryResults;")]
        global::org.drools.runtime.rule.QueryResults getQueryResults(global::java.lang.String par0, java.lang.Object[] par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lorg/drools/runtime/rule/QueryResults;")]
        global::org.drools.runtime.rule.QueryResults getQueryResults(global::java.lang.String par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;[Ljava/lang/Object;Lorg/drools/runtime/rule/ViewChangedEventLi" +
            "stener;)Lorg/drools/runtime/rule/LiveQuery;")]
        global::org.drools.runtime.rule.LiveQuery openLiveQuery(global::java.lang.String par0, java.lang.Object[] par1, global::org.drools.runtime.rule.ViewChangedEventListener par2);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class WorkingMemory_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.runtime.rule.@__WorkingMemory.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::org.drools.runtime.rule.WorkingMemory), typeof(global::org.drools.runtime.rule.WorkingMemory_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::org.drools.runtime.rule.WorkingMemory), typeof(global::org.drools.runtime.rule.WorkingMemory_))]
    internal sealed partial class @__WorkingMemory : global::java.lang.Object, global::org.drools.runtime.rule.WorkingMemory {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _getObject0;
        
        internal static global::net.sf.jni4net.jni.MethodId _insert1;
        
        internal static global::net.sf.jni4net.jni.MethodId _update2;
        
        internal static global::net.sf.jni4net.jni.MethodId _getFactHandle3;
        
        internal static global::net.sf.jni4net.jni.MethodId _getEntryPointId4;
        
        internal static global::net.sf.jni4net.jni.MethodId _retract5;
        
        internal static global::net.sf.jni4net.jni.MethodId _getObjects6;
        
        internal static global::net.sf.jni4net.jni.MethodId _getObjects7;
        
        internal static global::net.sf.jni4net.jni.MethodId _getFactHandles8;
        
        internal static global::net.sf.jni4net.jni.MethodId _getFactHandles9;
        
        internal static global::net.sf.jni4net.jni.MethodId _getFactCount10;
        
        internal static global::net.sf.jni4net.jni.MethodId _halt11;
        
        internal static global::net.sf.jni4net.jni.MethodId _getAgenda12;
        
        internal static global::net.sf.jni4net.jni.MethodId _getWorkingMemoryEntryPoint13;
        
        internal static global::net.sf.jni4net.jni.MethodId _getWorkingMemoryEntryPoints14;
        
        internal static global::net.sf.jni4net.jni.MethodId _getQueryResults15;
        
        internal static global::net.sf.jni4net.jni.MethodId _getQueryResults16;
        
        internal static global::net.sf.jni4net.jni.MethodId _openLiveQuery17;
        
        private @__WorkingMemory(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.runtime.rule.@__WorkingMemory.staticClass = @__class;
            global::org.drools.runtime.rule.@__WorkingMemory._getObject0 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getObject", "(Lorg/drools/runtime/rule/FactHandle;)Ljava/lang/Object;");
            global::org.drools.runtime.rule.@__WorkingMemory._insert1 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "insert", "(Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;");
            global::org.drools.runtime.rule.@__WorkingMemory._update2 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "update", "(Lorg/drools/runtime/rule/FactHandle;Ljava/lang/Object;)V");
            global::org.drools.runtime.rule.@__WorkingMemory._getFactHandle3 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getFactHandle", "(Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;");
            global::org.drools.runtime.rule.@__WorkingMemory._getEntryPointId4 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getEntryPointId", "()Ljava/lang/String;");
            global::org.drools.runtime.rule.@__WorkingMemory._retract5 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "retract", "(Lorg/drools/runtime/rule/FactHandle;)V");
            global::org.drools.runtime.rule.@__WorkingMemory._getObjects6 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getObjects", "(Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;");
            global::org.drools.runtime.rule.@__WorkingMemory._getObjects7 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getObjects", "()Ljava/util/Collection;");
            global::org.drools.runtime.rule.@__WorkingMemory._getFactHandles8 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getFactHandles", "(Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;");
            global::org.drools.runtime.rule.@__WorkingMemory._getFactHandles9 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getFactHandles", "()Ljava/util/Collection;");
            global::org.drools.runtime.rule.@__WorkingMemory._getFactCount10 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getFactCount", "()J");
            global::org.drools.runtime.rule.@__WorkingMemory._halt11 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "halt", "()V");
            global::org.drools.runtime.rule.@__WorkingMemory._getAgenda12 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getAgenda", "()Lorg/drools/runtime/rule/Agenda;");
            global::org.drools.runtime.rule.@__WorkingMemory._getWorkingMemoryEntryPoint13 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getWorkingMemoryEntryPoint", "(Ljava/lang/String;)Lorg/drools/runtime/rule/WorkingMemoryEntryPoint;");
            global::org.drools.runtime.rule.@__WorkingMemory._getWorkingMemoryEntryPoints14 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getWorkingMemoryEntryPoints", "()Ljava/util/Collection;");
            global::org.drools.runtime.rule.@__WorkingMemory._getQueryResults15 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getQueryResults", "(Ljava/lang/String;[Ljava/lang/Object;)Lorg/drools/runtime/rule/QueryResults;");
            global::org.drools.runtime.rule.@__WorkingMemory._getQueryResults16 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "getQueryResults", "(Ljava/lang/String;)Lorg/drools/runtime/rule/QueryResults;");
            global::org.drools.runtime.rule.@__WorkingMemory._openLiveQuery17 = @__env.GetMethodID(global::org.drools.runtime.rule.@__WorkingMemory.staticClass, "openLiveQuery", "(Ljava/lang/String;[Ljava/lang/Object;Lorg/drools/runtime/rule/ViewChangedEventLi" +
                    "stener;)Lorg/drools/runtime/rule/LiveQuery;");
        }
        
        public global::java.lang.Object getObject(global::org.drools.runtime.rule.FactHandle par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getObject0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.runtime.rule.FactHandle>(@__env, par0)));
            }
        }
        
        public global::org.drools.runtime.rule.FactHandle insert(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.FactHandle>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._insert1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        public void update(global::org.drools.runtime.rule.FactHandle par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::org.drools.runtime.rule.@__WorkingMemory._update2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.runtime.rule.FactHandle>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par1));
            }
        }
        
        public global::org.drools.runtime.rule.FactHandle getFactHandle(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.FactHandle>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getFactHandle3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        public global::java.lang.String getEntryPointId() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getEntryPointId4));
            }
        }
        
        public void retract(global::org.drools.runtime.rule.FactHandle par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.runtime.rule.@__WorkingMemory._retract5, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.runtime.rule.FactHandle>(@__env, par0));
            }
        }
        
        public global::java.util.Collection getObjects(global::org.drools.runtime.ObjectFilter par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Collection>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getObjects6, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.runtime.ObjectFilter>(@__env, par0)));
            }
        }
        
        public global::java.util.Collection getObjects() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Collection>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getObjects7));
            }
        }
        
        public global::java.util.Collection getFactHandles(global::org.drools.runtime.ObjectFilter par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Collection>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getFactHandles8, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.runtime.ObjectFilter>(@__env, par0)));
            }
        }
        
        public global::java.util.Collection getFactHandles() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Collection>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getFactHandles9));
            }
        }
        
        public long getFactCount() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::org.drools.runtime.rule.@__WorkingMemory._getFactCount10)));
            }
        }
        
        public void halt() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::org.drools.runtime.rule.@__WorkingMemory._halt11);
            }
        }
        
        public global::org.drools.runtime.rule.Agenda getAgenda() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Agenda>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getAgenda12));
            }
        }
        
        public global::org.drools.runtime.rule.WorkingMemoryEntryPoint getWorkingMemoryEntryPoint(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemoryEntryPoint>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getWorkingMemoryEntryPoint13, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public global::java.util.Collection getWorkingMemoryEntryPoints() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Collection>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getWorkingMemoryEntryPoints14));
            }
        }
        
        public global::org.drools.runtime.rule.QueryResults getQueryResults(global::java.lang.String par0, java.lang.Object[] par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.QueryResults>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getQueryResults15, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParArrayFullC2J<java.lang.Object[], global::java.lang.Object>(@__env, par1)));
            }
        }
        
        public global::org.drools.runtime.rule.QueryResults getQueryResults(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.QueryResults>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._getQueryResults16, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public global::org.drools.runtime.rule.LiveQuery openLiveQuery(global::java.lang.String par0, java.lang.Object[] par1, global::org.drools.runtime.rule.ViewChangedEventListener par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.LiveQuery>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__WorkingMemory._openLiveQuery17, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParArrayFullC2J<java.lang.Object[], global::java.lang.Object>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.runtime.rule.ViewChangedEventListener>(@__env, par2)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__WorkingMemory);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getObject", "getObject0", "(Lorg/drools/runtime/rule/FactHandle;)Ljava/lang/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "insert", "insert1", "(Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "update", "update2", "(Lorg/drools/runtime/rule/FactHandle;Ljava/lang/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFactHandle", "getFactHandle3", "(Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getEntryPointId", "getEntryPointId4", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "retract", "retract5", "(Lorg/drools/runtime/rule/FactHandle;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getObjects", "getObjects6", "(Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getObjects", "getObjects7", "()Ljava/util/Collection;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFactHandles", "getFactHandles8", "(Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFactHandles", "getFactHandles9", "()Ljava/util/Collection;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFactCount", "getFactCount10", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "halt", "halt11", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAgenda", "getAgenda12", "()Lorg/drools/runtime/rule/Agenda;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getWorkingMemoryEntryPoint", "getWorkingMemoryEntryPoint13", "(Ljava/lang/String;)Lorg/drools/runtime/rule/WorkingMemoryEntryPoint;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getWorkingMemoryEntryPoints", "getWorkingMemoryEntryPoints14", "()Ljava/util/Collection;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getQueryResults", "getQueryResults15", "(Ljava/lang/String;[Ljava/lang/Object;)Lorg/drools/runtime/rule/QueryResults;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getQueryResults", "getQueryResults16", "(Ljava/lang/String;)Lorg/drools/runtime/rule/QueryResults;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "openLiveQuery", "openLiveQuery17", "(Ljava/lang/String;[Ljava/lang/Object;Lorg/drools/runtime/rule/ViewChangedEventLi" +
                        "stener;)Lorg/drools/runtime/rule/LiveQuery;"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getObject0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Lorg/drools/runtime/rule/FactHandle;)Ljava/lang/Object;
            // (Lorg/drools/runtime/rule/FactHandle;)Ljava/lang/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.lang.Object>(@__env, ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).getObject(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.FactHandle>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle insert1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;
            // (Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.FactHandle>(@__env, ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).insert(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void update2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Lorg/drools/runtime/rule/FactHandle;Ljava/lang/Object;)V
            // (Lorg/drools/runtime/rule/FactHandle;Ljava/lang/Object;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).update(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.FactHandle>(@__env, par0), global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, par1));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getFactHandle3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;
            // (Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.FactHandle>(@__env, ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).getFactHandle(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getEntryPointId4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).getEntryPointId());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void retract5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Lorg/drools/runtime/rule/FactHandle;)V
            // (Lorg/drools/runtime/rule/FactHandle;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).retract(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.FactHandle>(@__env, par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getObjects6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;
            // (Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.Collection>(@__env, ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).getObjects(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.ObjectFilter>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getObjects7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/Collection;
            // ()Ljava/util/Collection;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.Collection>(@__env, ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).getObjects());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getFactHandles8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;
            // (Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.Collection>(@__env, ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).getFactHandles(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.ObjectFilter>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getFactHandles9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/Collection;
            // ()Ljava/util/Collection;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.Collection>(@__env, ((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).getFactHandles());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getFactCount10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = ((long)(((global::org.drools.runtime.rule.WorkingMemoryEntryPoint)(@__real)).getFactCount()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void halt11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__real.halt();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getAgenda12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lorg/drools/runtime/rule/Agenda;
            // ()Lorg/drools/runtime/rule/Agenda;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.Agenda>(@__env, @__real.getAgenda());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getWorkingMemoryEntryPoint13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/WorkingMemoryEntryPoint;
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/WorkingMemoryEntryPoint;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.WorkingMemoryEntryPoint>(@__env, @__real.getWorkingMemoryEntryPoint(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getWorkingMemoryEntryPoints14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/Collection;
            // ()Ljava/util/Collection;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.Collection>(@__env, @__real.getWorkingMemoryEntryPoints());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getQueryResults15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Ljava/lang/String;[Ljava/lang/Object;)Lorg/drools/runtime/rule/QueryResults;
            // (Ljava/lang/String;[Ljava/lang/Object;)Lorg/drools/runtime/rule/QueryResults;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.QueryResults>(@__env, @__real.getQueryResults(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), global::net.sf.jni4net.utils.Convertor.ArrayFullJ2C<java.lang.Object[], global::java.lang.Object>(@__env, par1)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getQueryResults16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/QueryResults;
            // (Ljava/lang/String;)Lorg/drools/runtime/rule/QueryResults;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.QueryResults>(@__env, @__real.getQueryResults(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle openLiveQuery17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1, global::net.sf.jni4net.utils.JniLocalHandle par2) {
            // (Ljava/lang/String;[Ljava/lang/Object;Lorg/drools/runtime/rule/ViewChangedEventListener;)Lorg/drools/runtime/rule/LiveQuery;
            // (Ljava/lang/String;[Ljava/lang/Object;Lorg/drools/runtime/rule/ViewChangedEventListener;)Lorg/drools/runtime/rule/LiveQuery;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.WorkingMemory @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.WorkingMemory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.LiveQuery>(@__env, @__real.openLiveQuery(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), global::net.sf.jni4net.utils.Convertor.ArrayFullJ2C<java.lang.Object[], global::java.lang.Object>(@__env, par1), global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.ViewChangedEventListener>(@__env, par2)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.runtime.rule.@__WorkingMemory(@__env);
            }
        }
    }
    #endregion
}
