// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.drools.persistence.jpa;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class JPAKnowledgeService_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return org.drools.persistence.jpa.JPAKnowledgeService_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        org.drools.persistence.jpa.JPAKnowledgeService_.staticType = staticType;
    }
    //</generated-static>
}
