// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package java_.lang;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class Cloneable_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return java_.lang.Cloneable_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        java_.lang.Cloneable_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __Cloneable extends system.Object implements java.lang.Cloneable {
    
    protected __Cloneable(net.sf.jni4net.inj.INJEnv __env, int __handle) {
            super(__env, __handle);
    }
}
//</generated-proxy>
