//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.management {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface KnowledgeSessionMonitoringMBean {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/management/ObjectName;")]
        global::java.lang.Object getName();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        void reset();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        global::java.lang.String getKnowledgeBaseId();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        int getKnowledgeSessionId();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getTotalFactCount();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getTotalActivationsFired();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getTotalActivationsCancelled();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getTotalActivationsCreated();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getTotalFiringTime();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()D")]
        double getAverageFiringTime();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/lang/String;")]
        global::java.lang.String getStatsForRule(global::java.lang.String par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/Date;")]
        global::java.lang.Object getLastReset();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/Map;")]
        global::java.util.Map getStatsByRule();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getTotalProcessInstancesStarted();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getTotalProcessInstancesCompleted();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/lang/String;")]
        global::java.lang.String getStatsForProcess(global::java.lang.String par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/Map;")]
        global::java.util.Map getStatsByProcess();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(J)Ljava/lang/String;")]
        global::java.lang.String getStatsForProcessInstance(long par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/Map;")]
        global::java.util.Map getStatsByProcessInstance();
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class KnowledgeSessionMonitoringMBean_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::org.drools.management.KnowledgeSessionMonitoringMBean), typeof(global::org.drools.management.KnowledgeSessionMonitoringMBean_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::org.drools.management.KnowledgeSessionMonitoringMBean), typeof(global::org.drools.management.KnowledgeSessionMonitoringMBean_))]
    internal sealed partial class @__KnowledgeSessionMonitoringMBean : global::java.lang.Object, global::org.drools.management.KnowledgeSessionMonitoringMBean {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _getName0;
        
        internal static global::net.sf.jni4net.jni.MethodId _reset1;
        
        internal static global::net.sf.jni4net.jni.MethodId _getKnowledgeBaseId2;
        
        internal static global::net.sf.jni4net.jni.MethodId _getKnowledgeSessionId3;
        
        internal static global::net.sf.jni4net.jni.MethodId _getTotalFactCount4;
        
        internal static global::net.sf.jni4net.jni.MethodId _getTotalActivationsFired5;
        
        internal static global::net.sf.jni4net.jni.MethodId _getTotalActivationsCancelled6;
        
        internal static global::net.sf.jni4net.jni.MethodId _getTotalActivationsCreated7;
        
        internal static global::net.sf.jni4net.jni.MethodId _getTotalFiringTime8;
        
        internal static global::net.sf.jni4net.jni.MethodId _getAverageFiringTime9;
        
        internal static global::net.sf.jni4net.jni.MethodId _getStatsForRule10;
        
        internal static global::net.sf.jni4net.jni.MethodId _getLastReset11;
        
        internal static global::net.sf.jni4net.jni.MethodId _getStatsByRule12;
        
        internal static global::net.sf.jni4net.jni.MethodId _getTotalProcessInstancesStarted13;
        
        internal static global::net.sf.jni4net.jni.MethodId _getTotalProcessInstancesCompleted14;
        
        internal static global::net.sf.jni4net.jni.MethodId _getStatsForProcess15;
        
        internal static global::net.sf.jni4net.jni.MethodId _getStatsByProcess16;
        
        internal static global::net.sf.jni4net.jni.MethodId _getStatsForProcessInstance17;
        
        internal static global::net.sf.jni4net.jni.MethodId _getStatsByProcessInstance18;
        
        private @__KnowledgeSessionMonitoringMBean(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass = @__class;
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getName0 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getName", "()Ljavax/management/ObjectName;");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._reset1 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "reset", "()V");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getKnowledgeBaseId2 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getKnowledgeBaseId", "()Ljava/lang/String;");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getKnowledgeSessionId3 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getKnowledgeSessionId", "()I");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalFactCount4 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getTotalFactCount", "()J");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalActivationsFired5 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getTotalActivationsFired", "()J");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalActivationsCancelled6 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getTotalActivationsCancelled", "()J");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalActivationsCreated7 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getTotalActivationsCreated", "()J");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalFiringTime8 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getTotalFiringTime", "()J");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getAverageFiringTime9 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getAverageFiringTime", "()D");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsForRule10 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getStatsForRule", "(Ljava/lang/String;)Ljava/lang/String;");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getLastReset11 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getLastReset", "()Ljava/util/Date;");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsByRule12 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getStatsByRule", "()Ljava/util/Map;");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalProcessInstancesStarted13 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getTotalProcessInstancesStarted", "()J");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalProcessInstancesCompleted14 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getTotalProcessInstancesCompleted", "()J");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsForProcess15 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getStatsForProcess", "(Ljava/lang/String;)Ljava/lang/String;");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsByProcess16 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getStatsByProcess", "()Ljava/util/Map;");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsForProcessInstance17 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getStatsForProcessInstance", "(J)Ljava/lang/String;");
            global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsByProcessInstance18 = @__env.GetMethodID(global::org.drools.management.@__KnowledgeSessionMonitoringMBean.staticClass, "getStatsByProcessInstance", "()Ljava/util/Map;");
        }
        
        public global::java.lang.Object getName() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getName0));
            }
        }
        
        public void reset() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._reset1);
            }
        }
        
        public global::java.lang.String getKnowledgeBaseId() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getKnowledgeBaseId2));
            }
        }
        
        public int getKnowledgeSessionId() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getKnowledgeSessionId3)));
            }
        }
        
        public long getTotalFactCount() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalFactCount4)));
            }
        }
        
        public long getTotalActivationsFired() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalActivationsFired5)));
            }
        }
        
        public long getTotalActivationsCancelled() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalActivationsCancelled6)));
            }
        }
        
        public long getTotalActivationsCreated() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalActivationsCreated7)));
            }
        }
        
        public long getTotalFiringTime() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalFiringTime8)));
            }
        }
        
        public double getAverageFiringTime() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((double)(@__env.CallDoubleMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getAverageFiringTime9)));
            }
        }
        
        public global::java.lang.String getStatsForRule(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsForRule10, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public global::java.lang.Object getLastReset() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getLastReset11));
            }
        }
        
        public global::java.util.Map getStatsByRule() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Map>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsByRule12));
            }
        }
        
        public long getTotalProcessInstancesStarted() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalProcessInstancesStarted13)));
            }
        }
        
        public long getTotalProcessInstancesCompleted() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getTotalProcessInstancesCompleted14)));
            }
        }
        
        public global::java.lang.String getStatsForProcess(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsForProcess15, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public global::java.util.Map getStatsByProcess() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Map>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsByProcess16));
            }
        }
        
        public global::java.lang.String getStatsForProcessInstance(long par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsForProcessInstance17, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        public global::java.util.Map getStatsByProcessInstance() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Map>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.management.@__KnowledgeSessionMonitoringMBean._getStatsByProcessInstance18));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__KnowledgeSessionMonitoringMBean);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getName", "getName0", "()Ljavax/management/ObjectName;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "reset", "reset1", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getKnowledgeBaseId", "getKnowledgeBaseId2", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getKnowledgeSessionId", "getKnowledgeSessionId3", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTotalFactCount", "getTotalFactCount4", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTotalActivationsFired", "getTotalActivationsFired5", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTotalActivationsCancelled", "getTotalActivationsCancelled6", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTotalActivationsCreated", "getTotalActivationsCreated7", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTotalFiringTime", "getTotalFiringTime8", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAverageFiringTime", "getAverageFiringTime9", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getStatsForRule", "getStatsForRule10", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getLastReset", "getLastReset11", "()Ljava/util/Date;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getStatsByRule", "getStatsByRule12", "()Ljava/util/Map;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTotalProcessInstancesStarted", "getTotalProcessInstancesStarted13", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTotalProcessInstancesCompleted", "getTotalProcessInstancesCompleted14", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getStatsForProcess", "getStatsForProcess15", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getStatsByProcess", "getStatsByProcess16", "()Ljava/util/Map;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getStatsForProcessInstance", "getStatsForProcessInstance17", "(J)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getStatsByProcessInstance", "getStatsByProcessInstance18", "()Ljava/util/Map;"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getName0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljavax/management/ObjectName;
            // ()Ljava/lang/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getName());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void reset1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__real.reset();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getKnowledgeBaseId2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getKnowledgeBaseId());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int getKnowledgeSessionId3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((int)(@__real.getKnowledgeSessionId()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getTotalFactCount4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((long)(@__real.getTotalFactCount()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getTotalActivationsFired5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((long)(@__real.getTotalActivationsFired()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getTotalActivationsCancelled6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((long)(@__real.getTotalActivationsCancelled()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getTotalActivationsCreated7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((long)(@__real.getTotalActivationsCreated()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getTotalFiringTime8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((long)(@__real.getTotalFiringTime()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double getAverageFiringTime9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((double)(@__real.getAverageFiringTime()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getStatsForRule10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (Ljava/lang/String;)Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getStatsForRule(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getLastReset11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/Date;
            // ()Ljava/lang/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getLastReset());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getStatsByRule12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/Map;
            // ()Ljava/util/Map;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.Map>(@__env, @__real.getStatsByRule());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getTotalProcessInstancesStarted13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((long)(@__real.getTotalProcessInstancesStarted()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getTotalProcessInstancesCompleted14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = ((long)(@__real.getTotalProcessInstancesCompleted()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getStatsForProcess15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (Ljava/lang/String;)Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getStatsForProcess(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getStatsByProcess16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/Map;
            // ()Ljava/util/Map;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.Map>(@__env, @__real.getStatsByProcess());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getStatsForProcessInstance17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, long par0) {
            // (J)Ljava/lang/String;
            // (J)Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getStatsForProcessInstance(par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getStatsByProcessInstance18(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/Map;
            // ()Ljava/util/Map;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.management.KnowledgeSessionMonitoringMBean @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.management.KnowledgeSessionMonitoringMBean>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.Map>(@__env, @__real.getStatsByProcessInstance());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.management.@__KnowledgeSessionMonitoringMBean(@__env);
            }
        }
    }
    #endregion
}
