// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.drools.runtime.rule;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class WorkingMemory_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return org.drools.runtime.rule.WorkingMemory_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        org.drools.runtime.rule.WorkingMemory_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __WorkingMemory extends system.Object implements org.drools.runtime.rule.WorkingMemory {
    
    protected __WorkingMemory(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/rule/FactHandle;)Ljava/lang/Object;")
    public native java.lang.Object getObject(org.drools.runtime.rule.FactHandle par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;")
    public native org.drools.runtime.rule.FactHandle insert(java.lang.Object par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/rule/FactHandle;Ljava/lang/Object;)V")
    public native void update(org.drools.runtime.rule.FactHandle par0, java.lang.Object par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Lorg/drools/runtime/rule/FactHandle;")
    public native org.drools.runtime.rule.FactHandle getFactHandle(java.lang.Object par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getEntryPointId();
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/rule/FactHandle;)V")
    public native void retract(org.drools.runtime.rule.FactHandle par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;")
    public native java.util.Collection getObjects(org.drools.runtime.ObjectFilter par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Collection;")
    public native java.util.Collection getObjects();
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/ObjectFilter;)Ljava/util/Collection;")
    public native java.util.Collection getFactHandles(org.drools.runtime.ObjectFilter par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Collection;")
    public native java.util.Collection getFactHandles();
    
    @net.sf.jni4net.attributes.ClrMethod("()J")
    public native long getFactCount();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void halt();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lorg/drools/runtime/rule/Agenda;")
    public native org.drools.runtime.rule.Agenda getAgenda();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lorg/drools/runtime/rule/WorkingMemoryEntryPoint;")
    public native org.drools.runtime.rule.WorkingMemoryEntryPoint getWorkingMemoryEntryPoint(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Collection;")
    public native java.util.Collection getWorkingMemoryEntryPoints();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;[Ljava/lang/Object;)Lorg/drools/runtime/rule/QueryResults;")
    public native org.drools.runtime.rule.QueryResults getQueryResults(java.lang.String par0, java.lang.Object[] par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lorg/drools/runtime/rule/QueryResults;")
    public native org.drools.runtime.rule.QueryResults getQueryResults(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;[Ljava/lang/Object;Lorg/drools/runtime/rule/ViewChangedEventListener;)Lorg/drools/runtime/rule/LiveQuery;")
    public native org.drools.runtime.rule.LiveQuery openLiveQuery(java.lang.String par0, java.lang.Object[] par1, org.drools.runtime.rule.ViewChangedEventListener par2);
}
//</generated-proxy>
