//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class SystemEventListenerFactory : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _setSystemEventListener0;
        
        internal static global::net.sf.jni4net.jni.MethodId _getSystemEventListener1;
        
        internal static global::net.sf.jni4net.jni.MethodId @__ctorSystemEventListenerFactory2;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public SystemEventListenerFactory() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::org.drools.SystemEventListenerFactory.staticClass, global::org.drools.SystemEventListenerFactory.@__ctorSystemEventListenerFactory2, this);
            }
        }
        
        protected SystemEventListenerFactory(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.SystemEventListenerFactory.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.SystemEventListenerFactory.staticClass = @__class;
            global::org.drools.SystemEventListenerFactory._setSystemEventListener0 = @__env.GetStaticMethodID(global::org.drools.SystemEventListenerFactory.staticClass, "setSystemEventListener", "(Lorg/drools/SystemEventListener;)V");
            global::org.drools.SystemEventListenerFactory._getSystemEventListener1 = @__env.GetStaticMethodID(global::org.drools.SystemEventListenerFactory.staticClass, "getSystemEventListener", "()Lorg/drools/SystemEventListener;");
            global::org.drools.SystemEventListenerFactory.@__ctorSystemEventListenerFactory2 = @__env.GetMethodID(global::org.drools.SystemEventListenerFactory.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/SystemEventListener;)V")]
        public static void setSystemEventListener(global::org.drools.SystemEventListener par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::org.drools.SystemEventListenerFactory.staticClass, global::org.drools.SystemEventListenerFactory._setSystemEventListener0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.SystemEventListener>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/SystemEventListener;")]
        public static global::org.drools.SystemEventListener getSystemEventListener() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.SystemEventListener>(@__env, @__env.CallStaticObjectMethodPtr(global::org.drools.SystemEventListenerFactory.staticClass, global::org.drools.SystemEventListenerFactory._getSystemEventListener1));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.SystemEventListenerFactory(@__env);
            }
        }
    }
    #endregion
}
