// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.collections;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IDictionaryEnumerator_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return system.collections.IDictionaryEnumerator_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.collections.IDictionaryEnumerator_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IDictionaryEnumerator extends system.Object implements system.collections.IDictionaryEnumerator {
    
    protected __IDictionaryEnumerator(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean MoveNext();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getCurrent();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Reset();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getKey();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getValue();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Collections/DictionaryEntry;")
    public native system.ValueType getEntry();
}
//</generated-proxy>
