// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.runtime.serialization;

@net.sf.jni4net.attributes.ClrType
public class SerializationInfo extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected SerializationInfo(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/Type;LSystem/Runtime/Serialization/IFormatterConverter;)V")
    public SerializationInfo(system.Type type, system.Object converter) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.runtime.serialization.SerializationInfo.__ctorSerializationInfo0(this, type, converter);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/Type;Lsystem/Object;)V")
    private native static void __ctorSerializationInfo0(net.sf.jni4net.inj.IClrProxy thiz, system.Type type, system.Object converter);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getFullTypeName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setFullTypeName(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAssemblyName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAssemblyName(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Type;)V")
    public native void SetType(system.Type type);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getMemberCount();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Runtime/Serialization/SerializationInfoEnumerator;")
    public native system.Object GetEnumerator();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/Object;LSystem/Type;)V")
    public native void AddValue(java.lang.String name, system.Object value, system.Type type);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/Object;)V")
    public native void AddValue(java.lang.String name, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;Z)V")
    public native void AddValue(java.lang.String name, boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;C)V")
    public native void AddValue(java.lang.String name, char value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/SByte;)V")
    public native void AddValue(java.lang.String name, byte value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;S)V")
    public native void AddValue(java.lang.String name, short value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;I)V")
    public native void AddValue(java.lang.String name, int value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;J)V")
    public native void AddValue(java.lang.String name, long value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;F)V")
    public native void AddValue(java.lang.String name, float value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;D)V")
    public native void AddValue(java.lang.String name, double value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/Decimal;)V")
    public native void AddValue(java.lang.String name, system.Decimal value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/DateTime;)V")
    public native void AddValue(java.lang.String name, system.DateTime value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/Type;)LSystem/Object;")
    public native system.Object GetValue(java.lang.String name, system.Type type);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Z")
    public native boolean GetBoolean(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)C")
    public native char GetChar(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/SByte;")
    public native byte GetSByte(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)B")
    public native byte GetByte(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)S")
    public native short GetInt16(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/UInt16;")
    public native short GetUInt16(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/UInt32;")
    public native int GetUInt32(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)J")
    public native long GetInt64(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/UInt64;")
    public native long GetUInt64(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)F")
    public native float GetSingle(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)D")
    public native double GetDouble(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/Decimal;")
    public native system.Decimal GetDecimal(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/DateTime;")
    public native system.DateTime GetDateTime(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)I")
    public native int GetInt32(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    public native java.lang.String GetString(java.lang.String name);
    
    public static system.Type typeof() {
        return system.runtime.serialization.SerializationInfo.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.runtime.serialization.SerializationInfo.staticType = staticType;
    }
    //</generated-proxy>
}
