//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.conf {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class SequentialAgendaOption : global::java.lang.Object, global::org.drools.conf.SingleValueKnowledgeBaseOption {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _getPropertyName0;
        
        internal static global::net.sf.jni4net.jni.MethodId _valueOf1;
        
        internal static global::net.sf.jni4net.jni.MethodId _values2;
        
        internal static global::net.sf.jni4net.jni.FieldId _SEQUENTIAL3;
        
        internal static global::net.sf.jni4net.jni.FieldId _DYNAMIC4;
        
        internal static global::net.sf.jni4net.jni.FieldId _PROPERTY_NAME5;
        
        protected SequentialAgendaOption(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.conf.SequentialAgendaOption.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lorg/drools/conf/SequentialAgendaOption;")]
        public static global::org.drools.conf.SequentialAgendaOption SEQUENTIAL {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::org.drools.conf.SequentialAgendaOption>(@__env, @__env.GetStaticObjectFieldPtr(global::org.drools.conf.SequentialAgendaOption.staticClass, global::org.drools.conf.SequentialAgendaOption._SEQUENTIAL3));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lorg/drools/conf/SequentialAgendaOption;")]
        public static global::org.drools.conf.SequentialAgendaOption DYNAMIC {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::org.drools.conf.SequentialAgendaOption>(@__env, @__env.GetStaticObjectFieldPtr(global::org.drools.conf.SequentialAgendaOption.staticClass, global::org.drools.conf.SequentialAgendaOption._DYNAMIC4));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_NAME {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::org.drools.conf.SequentialAgendaOption.staticClass, global::org.drools.conf.SequentialAgendaOption._PROPERTY_NAME5));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.conf.SequentialAgendaOption.staticClass = @__class;
            global::org.drools.conf.SequentialAgendaOption._getPropertyName0 = @__env.GetMethodID(global::org.drools.conf.SequentialAgendaOption.staticClass, "getPropertyName", "()Ljava/lang/String;");
            global::org.drools.conf.SequentialAgendaOption._valueOf1 = @__env.GetStaticMethodID(global::org.drools.conf.SequentialAgendaOption.staticClass, "valueOf", "(Ljava/lang/String;)Lorg/drools/conf/SequentialAgendaOption;");
            global::org.drools.conf.SequentialAgendaOption._values2 = @__env.GetStaticMethodID(global::org.drools.conf.SequentialAgendaOption.staticClass, "values", "()[Lorg/drools/conf/SequentialAgendaOption;");
            global::org.drools.conf.SequentialAgendaOption._SEQUENTIAL3 = @__env.GetStaticFieldID(global::org.drools.conf.SequentialAgendaOption.staticClass, "SEQUENTIAL", "Lorg/drools/conf/SequentialAgendaOption;");
            global::org.drools.conf.SequentialAgendaOption._DYNAMIC4 = @__env.GetStaticFieldID(global::org.drools.conf.SequentialAgendaOption.staticClass, "DYNAMIC", "Lorg/drools/conf/SequentialAgendaOption;");
            global::org.drools.conf.SequentialAgendaOption._PROPERTY_NAME5 = @__env.GetStaticFieldID(global::org.drools.conf.SequentialAgendaOption.staticClass, "PROPERTY_NAME", "Ljava/lang/String;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getPropertyName() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.conf.SequentialAgendaOption._getPropertyName0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lorg/drools/conf/SequentialAgendaOption;")]
        public static global::org.drools.conf.SequentialAgendaOption valueOf(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::org.drools.conf.SequentialAgendaOption>(@__env, @__env.CallStaticObjectMethodPtr(global::org.drools.conf.SequentialAgendaOption.staticClass, global::org.drools.conf.SequentialAgendaOption._valueOf1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Lorg/drools/conf/SequentialAgendaOption;")]
        public static org.drools.conf.SequentialAgendaOption[] values() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2Cp<org.drools.conf.SequentialAgendaOption[], global::org.drools.conf.SequentialAgendaOption>(@__env, @__env.CallStaticObjectMethodPtr(global::org.drools.conf.SequentialAgendaOption.staticClass, global::org.drools.conf.SequentialAgendaOption._values2));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.conf.SequentialAgendaOption(@__env);
            }
        }
    }
    #endregion
}
