// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.drools.runtime.process;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class WorkItemHandler_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return org.drools.runtime.process.WorkItemHandler_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        org.drools.runtime.process.WorkItemHandler_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __WorkItemHandler extends system.Object implements org.drools.runtime.process.WorkItemHandler {
    
    protected __WorkItemHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/process/WorkItem;Lorg/drools/runtime/process/WorkItemManager;)V")
    public native void abortWorkItem(org.drools.runtime.process.WorkItem par0, org.drools.runtime.process.WorkItemManager par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/process/WorkItem;Lorg/drools/runtime/process/WorkItemManager;)V")
    public native void executeWorkItem(org.drools.runtime.process.WorkItem par0, org.drools.runtime.process.WorkItemManager par1);
}
//</generated-proxy>
