// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.drools.event.rule;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class WorkingMemoryEventManager_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return org.drools.event.rule.WorkingMemoryEventManager_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        org.drools.event.rule.WorkingMemoryEventManager_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __WorkingMemoryEventManager extends system.Object implements org.drools.event.rule.WorkingMemoryEventManager {
    
    protected __WorkingMemoryEventManager(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/event/rule/AgendaEventListener;)V")
    public native void addEventListener(org.drools.event.rule.AgendaEventListener par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/event/rule/WorkingMemoryEventListener;)V")
    public native void addEventListener(org.drools.event.rule.WorkingMemoryEventListener par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/event/rule/AgendaEventListener;)V")
    public native void removeEventListener(org.drools.event.rule.AgendaEventListener par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/event/rule/WorkingMemoryEventListener;)V")
    public native void removeEventListener(org.drools.event.rule.WorkingMemoryEventListener par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Collection;")
    public native java.util.Collection getWorkingMemoryEventListeners();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Collection;")
    public native java.util.Collection getAgendaEventListeners();
}
//</generated-proxy>
