//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.@event.knowledgebase {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class DefaultKnowledgeBaseEventListener : global::java.lang.Object, global::org.drools.@event.knowledgebase.KnowledgeBaseEventListener {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeKnowledgePackageAdded0;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterKnowledgePackageAdded1;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeKnowledgePackageRemoved2;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterKnowledgePackageRemoved3;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeKnowledgeBaseLocked4;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterKnowledgeBaseLocked5;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeKnowledgeBaseUnlocked6;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterKnowledgeBaseUnlocked7;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeRuleAdded8;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterRuleAdded9;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeRuleRemoved10;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterRuleRemoved11;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeFunctionRemoved12;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterFunctionRemoved13;
        
        internal static global::net.sf.jni4net.jni.MethodId @__ctorDefaultKnowledgeBaseEventListener14;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public DefaultKnowledgeBaseEventListener() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.@__ctorDefaultKnowledgeBaseEventListener14, this);
            }
        }
        
        protected DefaultKnowledgeBaseEventListener(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass = @__class;
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeKnowledgePackageAdded0 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "beforeKnowledgePackageAdded", "(Lorg/drools/event/knowledgebase/BeforeKnowledgePackageAddedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterKnowledgePackageAdded1 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "afterKnowledgePackageAdded", "(Lorg/drools/event/knowledgebase/AfterKnowledgePackageAddedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeKnowledgePackageRemoved2 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "beforeKnowledgePackageRemoved", "(Lorg/drools/event/knowledgebase/BeforeKnowledgePackageRemovedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterKnowledgePackageRemoved3 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "afterKnowledgePackageRemoved", "(Lorg/drools/event/knowledgebase/AfterKnowledgePackageRemovedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeKnowledgeBaseLocked4 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "beforeKnowledgeBaseLocked", "(Lorg/drools/event/knowledgebase/BeforeKnowledgeBaseLockedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterKnowledgeBaseLocked5 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "afterKnowledgeBaseLocked", "(Lorg/drools/event/knowledgebase/AfterKnowledgeBaseLockedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeKnowledgeBaseUnlocked6 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "beforeKnowledgeBaseUnlocked", "(Lorg/drools/event/knowledgebase/BeforeKnowledgeBaseUnlockedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterKnowledgeBaseUnlocked7 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "afterKnowledgeBaseUnlocked", "(Lorg/drools/event/knowledgebase/AfterKnowledgeBaseUnlockedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeRuleAdded8 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "beforeRuleAdded", "(Lorg/drools/event/knowledgebase/BeforeRuleAddedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterRuleAdded9 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "afterRuleAdded", "(Lorg/drools/event/knowledgebase/AfterRuleAddedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeRuleRemoved10 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "beforeRuleRemoved", "(Lorg/drools/event/knowledgebase/BeforeRuleRemovedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterRuleRemoved11 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "afterRuleRemoved", "(Lorg/drools/event/knowledgebase/AfterRuleRemovedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeFunctionRemoved12 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "beforeFunctionRemoved", "(Lorg/drools/event/knowledgebase/BeforeFunctionRemovedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterFunctionRemoved13 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "afterFunctionRemoved", "(Lorg/drools/event/knowledgebase/AfterFunctionRemovedEvent;)V");
            global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.@__ctorDefaultKnowledgeBaseEventListener14 = @__env.GetMethodID(global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/BeforeKnowledgePackageAddedEvent;)V")]
        public virtual void beforeKnowledgePackageAdded(global::org.drools.@event.knowledgebase.BeforeKnowledgePackageAddedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeKnowledgePackageAdded0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.BeforeKnowledgePackageAddedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/AfterKnowledgePackageAddedEvent;)V")]
        public virtual void afterKnowledgePackageAdded(global::org.drools.@event.knowledgebase.AfterKnowledgePackageAddedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterKnowledgePackageAdded1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.AfterKnowledgePackageAddedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/BeforeKnowledgePackageRemovedEvent;)V")]
        public virtual void beforeKnowledgePackageRemoved(global::org.drools.@event.knowledgebase.BeforeKnowledgePackageRemovedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeKnowledgePackageRemoved2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.BeforeKnowledgePackageRemovedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/AfterKnowledgePackageRemovedEvent;)V")]
        public virtual void afterKnowledgePackageRemoved(global::org.drools.@event.knowledgebase.AfterKnowledgePackageRemovedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterKnowledgePackageRemoved3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.AfterKnowledgePackageRemovedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/BeforeKnowledgeBaseLockedEvent;)V")]
        public virtual void beforeKnowledgeBaseLocked(global::org.drools.@event.knowledgebase.BeforeKnowledgeBaseLockedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeKnowledgeBaseLocked4, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.BeforeKnowledgeBaseLockedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/AfterKnowledgeBaseLockedEvent;)V")]
        public virtual void afterKnowledgeBaseLocked(global::org.drools.@event.knowledgebase.AfterKnowledgeBaseLockedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterKnowledgeBaseLocked5, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.AfterKnowledgeBaseLockedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/BeforeKnowledgeBaseUnlockedEvent;)V")]
        public virtual void beforeKnowledgeBaseUnlocked(global::org.drools.@event.knowledgebase.BeforeKnowledgeBaseUnlockedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeKnowledgeBaseUnlocked6, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.BeforeKnowledgeBaseUnlockedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/AfterKnowledgeBaseUnlockedEvent;)V")]
        public virtual void afterKnowledgeBaseUnlocked(global::org.drools.@event.knowledgebase.AfterKnowledgeBaseUnlockedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterKnowledgeBaseUnlocked7, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.AfterKnowledgeBaseUnlockedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/BeforeRuleAddedEvent;)V")]
        public virtual void beforeRuleAdded(global::org.drools.@event.knowledgebase.BeforeRuleAddedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeRuleAdded8, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.BeforeRuleAddedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/AfterRuleAddedEvent;)V")]
        public virtual void afterRuleAdded(global::org.drools.@event.knowledgebase.AfterRuleAddedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterRuleAdded9, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.AfterRuleAddedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/BeforeRuleRemovedEvent;)V")]
        public virtual void beforeRuleRemoved(global::org.drools.@event.knowledgebase.BeforeRuleRemovedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeRuleRemoved10, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.BeforeRuleRemovedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/AfterRuleRemovedEvent;)V")]
        public virtual void afterRuleRemoved(global::org.drools.@event.knowledgebase.AfterRuleRemovedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterRuleRemoved11, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.AfterRuleRemovedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/BeforeFunctionRemovedEvent;)V")]
        public virtual void beforeFunctionRemoved(global::org.drools.@event.knowledgebase.BeforeFunctionRemovedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._beforeFunctionRemoved12, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.BeforeFunctionRemovedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/knowledgebase/AfterFunctionRemovedEvent;)V")]
        public virtual void afterFunctionRemoved(global::org.drools.@event.knowledgebase.AfterFunctionRemovedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener._afterFunctionRemoved13, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.knowledgebase.AfterFunctionRemovedEvent>(@__env, par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.@event.knowledgebase.DefaultKnowledgeBaseEventListener(@__env);
            }
        }
    }
    #endregion
}
