// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.drools.io;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class ResourceFactoryService_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return org.drools.io.ResourceFactoryService_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        org.drools.io.ResourceFactoryService_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __ResourceFactoryService extends system.Object implements org.drools.io.ResourceFactoryService {
    
    protected __ResourceFactoryService(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()Lorg/drools/io/ResourceChangeNotifier;")
    public native org.drools.io.ResourceChangeNotifier getResourceChangeNotifierService();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lorg/drools/io/ResourceChangeScanner;")
    public native org.drools.io.ResourceChangeScanner getResourceChangeScannerService();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newUrlResource(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/net/URL;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newUrlResource(java.net.URL par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newFileSystemResource(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/io/File;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newFileSystemResource(java.io.File par0);
    
    @net.sf.jni4net.attributes.ClrMethod("([B)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newByteArrayResource(byte[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/io/InputStream;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newInputStreamResource(java.io.InputStream par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;Ljava/lang/String;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newReaderResource(java.io.Reader par0, java.lang.String par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newReaderResource(java.io.Reader par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/ClassLoader;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newClassPathResource(java.lang.String par0, java.lang.ClassLoader par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/Class;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newClassPathResource(java.lang.String par0, java.lang.Class par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lorg/drools/io/Resource;")
    public native org.drools.io.Resource newClassPathResource(java.lang.String par0);
}
//</generated-proxy>
