//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.tutorials.banking {
    
    
    #region Component Designer generated code 
    public partial class Cashflow_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.tutorials.banking.@__Cashflow.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::org.drools.tutorials.banking.Cashflow), typeof(global::org.drools.tutorials.banking.Cashflow_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::org.drools.tutorials.banking.Cashflow), typeof(global::org.drools.tutorials.banking.Cashflow_))]
    internal sealed partial class @__Cashflow : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Cashflow(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.tutorials.banking.@__Cashflow.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Cashflow);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDate", "Date0", "()Lsystem/DateTime;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setDate", "Date1", "(Lsystem/DateTime;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAmount", "Amount2", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAmount", "Amount3", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorCashflow0", "__ctorCashflow0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorCashflow1", "__ctorCashflow1", "(Lnet/sf/jni4net/inj/IClrProxy;Ljava/lang/String;D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorCashflow2", "__ctorCashflow2", "(Lnet/sf/jni4net/inj/IClrProxy;Lsystem/DateTime;D)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Date0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/DateTime;
            // ()LSystem/DateTime;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.tutorials.banking.Cashflow @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::org.drools.tutorials.banking.Cashflow>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.DateTime>(@__env, @__real.Date);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Date1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/DateTime;)V
            // (LSystem/DateTime;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.tutorials.banking.Cashflow @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::org.drools.tutorials.banking.Cashflow>(@__env, @__obj);
            @__real.Date = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.DateTime>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double Amount2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::org.drools.tutorials.banking.Cashflow @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::org.drools.tutorials.banking.Cashflow>(@__env, @__obj);
            @__return = ((double)(@__real.Amount));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Amount3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double value) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.tutorials.banking.Cashflow @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::org.drools.tutorials.banking.Cashflow>(@__env, @__obj);
            @__real.Amount = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorCashflow0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.tutorials.banking.Cashflow @__real = new global::org.drools.tutorials.banking.Cashflow();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorCashflow1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle date, double amount) {
            // (Ljava/lang/String;D)V
            // (LSystem/String;D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.tutorials.banking.Cashflow @__real = new global::org.drools.tutorials.banking.Cashflow(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, date), amount);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorCashflow2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle date, double amount) {
            // (Lsystem/DateTime;D)V
            // (LSystem/DateTime;D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.tutorials.banking.Cashflow @__real = new global::org.drools.tutorials.banking.Cashflow(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.DateTime>(@__env, date), amount);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.tutorials.banking.@__Cashflow(@__env);
            }
        }
    }
    #endregion
}
