using System.CodeDom;
using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using net.sf.jni4net.proxygen.model;

namespace net.sf.jni4net.proxygen.writers
{
    class JVMWriter:IWriter
    {
        public void Write(GFile file, Repository repository)
        {
            file.DText = new StringBuilder();

            var buffer = new StringWriter(file.DText);

            ICodeGenerator codeGenerator = new JavaCodeGenerator();
            var cop = new CodeGeneratorOptions();
            var unit = new CodeCompileUnit();

            unit.Namespaces.Add(file.DNamespace);
            codeGenerator.GenerateCodeFromCompileUnit(unit, buffer, cop);
            buffer.Close();

            file.DText.Replace("This code was generated by a tool.",
                               "This code was generated by jni4net. See http://jni4net.sourceforge.net/ ");


        }
    }
}
