//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.@event.knowledgeagent {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class ChangeSetProcessingEvent : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _getChangeSet0;
        
        internal static global::net.sf.jni4net.jni.MethodId @__ctorChangeSetProcessingEvent1;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/ChangeSet;)V")]
        public ChangeSetProcessingEvent(global::org.drools.ChangeSet par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent.staticClass, global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent.@__ctorChangeSetProcessingEvent1, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.ChangeSet>(@__env, par0));
            }
        }
        
        protected ChangeSetProcessingEvent(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent.staticClass = @__class;
            global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent._getChangeSet0 = @__env.GetMethodID(global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent.staticClass, "getChangeSet", "()Lorg/drools/ChangeSet;");
            global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent.@__ctorChangeSetProcessingEvent1 = @__env.GetMethodID(global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent.staticClass, "<init>", "(Lorg/drools/ChangeSet;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/ChangeSet;")]
        public virtual global::org.drools.ChangeSet getChangeSet() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.ChangeSet>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent._getChangeSet0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.@event.knowledgeagent.ChangeSetProcessingEvent(@__env);
            }
        }
    }
    #endregion
}
