// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.drools.runtime.rule;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class StatefulRuleSession_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return org.drools.runtime.rule.StatefulRuleSession_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        org.drools.runtime.rule.StatefulRuleSession_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __StatefulRuleSession extends system.Object implements org.drools.runtime.rule.StatefulRuleSession {
    
    protected __StatefulRuleSession(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(I)I")
    public native int fireAllRules(int par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/rule/AgendaFilter;)I")
    public native int fireAllRules(org.drools.runtime.rule.AgendaFilter par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int fireAllRules();
    
    @net.sf.jni4net.attributes.ClrMethod("(Lorg/drools/runtime/rule/AgendaFilter;)V")
    public native void fireUntilHalt(org.drools.runtime.rule.AgendaFilter par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void fireUntilHalt();
}
//</generated-proxy>
