// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package net.sf.jni4net.tested;

@net.sf.jni4net.attributes.ClrType
public class ClrException extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ClrException(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ClrException() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        net.sf.jni4net.tested.ClrException.__ctorClrException0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorClrException0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void NoException();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void ThrowBack();
    
    public static system.Type typeof() {
        return net.sf.jni4net.tested.ClrException.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        net.sf.jni4net.tested.ClrException.staticType = staticType;
    }
    //</generated-proxy>
}
