//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.runtime.conf {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class WorkItemHandlerOption : global::java.lang.Object, global::org.drools.runtime.conf.MultiValueKnowledgeSessionOption {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _getPropertyName0;
        
        internal static global::net.sf.jni4net.jni.MethodId _getName1;
        
        internal static global::net.sf.jni4net.jni.MethodId _get2;
        
        internal static global::net.sf.jni4net.jni.MethodId _getHandler3;
        
        internal static global::net.sf.jni4net.jni.FieldId _PROPERTY_NAME4;
        
        protected WorkItemHandlerOption(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_NAME {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass, global::org.drools.runtime.conf.WorkItemHandlerOption._PROPERTY_NAME4));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass = @__class;
            global::org.drools.runtime.conf.WorkItemHandlerOption._getPropertyName0 = @__env.GetMethodID(global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass, "getPropertyName", "()Ljava/lang/String;");
            global::org.drools.runtime.conf.WorkItemHandlerOption._getName1 = @__env.GetMethodID(global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass, "getName", "()Ljava/lang/String;");
            global::org.drools.runtime.conf.WorkItemHandlerOption._get2 = @__env.GetStaticMethodID(global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass, "get", "(Ljava/lang/String;Lorg/drools/runtime/process/WorkItemHandler;)Lorg/drools/runti" +
                    "me/conf/WorkItemHandlerOption;");
            global::org.drools.runtime.conf.WorkItemHandlerOption._getHandler3 = @__env.GetMethodID(global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass, "getHandler", "()Lorg/drools/runtime/process/WorkItemHandler;");
            global::org.drools.runtime.conf.WorkItemHandlerOption._PROPERTY_NAME4 = @__env.GetStaticFieldID(global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass, "PROPERTY_NAME", "Ljava/lang/String;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getPropertyName() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.conf.WorkItemHandlerOption._getPropertyName0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getName() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.conf.WorkItemHandlerOption._getName1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Lorg/drools/runtime/process/WorkItemHandler;)Lorg/drools/runti" +
            "me/conf/WorkItemHandlerOption;")]
        public static global::org.drools.runtime.conf.WorkItemHandlerOption get(global::java.lang.String par0, global::org.drools.runtime.process.WorkItemHandler par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::org.drools.runtime.conf.WorkItemHandlerOption>(@__env, @__env.CallStaticObjectMethodPtr(global::org.drools.runtime.conf.WorkItemHandlerOption.staticClass, global::org.drools.runtime.conf.WorkItemHandlerOption._get2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.runtime.process.WorkItemHandler>(@__env, par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/runtime/process/WorkItemHandler;")]
        public virtual global::org.drools.runtime.process.WorkItemHandler getHandler() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.process.WorkItemHandler>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.conf.WorkItemHandlerOption._getHandler3));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.runtime.conf.WorkItemHandlerOption(@__env);
            }
        }
    }
    #endregion
}
