//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.builder {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface KnowledgeBuilderFactoryService : global::org.drools.Service {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/Properties;[Ljava/lang/ClassLoader;)Lorg/drools/builder/KnowledgeBuil" +
            "derConfiguration;")]
        global::org.drools.builder.KnowledgeBuilderConfiguration newKnowledgeBuilderConfiguration(global::java.util.Properties par0, java.lang.ClassLoader[] par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/builder/KnowledgeBuilderConfiguration;")]
        global::org.drools.builder.KnowledgeBuilderConfiguration newKnowledgeBuilderConfiguration();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/builder/DecisionTableConfiguration;")]
        global::org.drools.builder.DecisionTableConfiguration newDecisionTableConfiguration();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lorg/drools/builder/Knowledge" +
            "Builder;")]
        global::org.drools.builder.KnowledgeBuilder newKnowledgeBuilder(global::org.drools.builder.KnowledgeBuilderConfiguration par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/KnowledgeBase;)Lorg/drools/builder/KnowledgeBuilder;")]
        global::org.drools.builder.KnowledgeBuilder newKnowledgeBuilder(global::org.drools.KnowledgeBase par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/KnowledgeBase;Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lor" +
            "g/drools/builder/KnowledgeBuilder;")]
        global::org.drools.builder.KnowledgeBuilder newKnowledgeBuilder(global::org.drools.KnowledgeBase par0, global::org.drools.builder.KnowledgeBuilderConfiguration par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/builder/KnowledgeBuilder;")]
        global::org.drools.builder.KnowledgeBuilder newKnowledgeBuilder();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/sun/tools/xjc/Options;Ljava/lang/String;)Lorg/drools/builder/JaxbConfigurat" +
            "ion;")]
        global::org.drools.builder.JaxbConfiguration newJaxbConfiguration(global::java.lang.Object par0, global::java.lang.String par1);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class KnowledgeBuilderFactoryService_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::org.drools.builder.KnowledgeBuilderFactoryService), typeof(global::org.drools.builder.KnowledgeBuilderFactoryService_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::org.drools.builder.KnowledgeBuilderFactoryService), typeof(global::org.drools.builder.KnowledgeBuilderFactoryService_))]
    internal sealed partial class @__KnowledgeBuilderFactoryService : global::java.lang.Object, global::org.drools.builder.KnowledgeBuilderFactoryService {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _newKnowledgeBuilderConfiguration0;
        
        internal static global::net.sf.jni4net.jni.MethodId _newKnowledgeBuilderConfiguration1;
        
        internal static global::net.sf.jni4net.jni.MethodId _newDecisionTableConfiguration2;
        
        internal static global::net.sf.jni4net.jni.MethodId _newKnowledgeBuilder3;
        
        internal static global::net.sf.jni4net.jni.MethodId _newKnowledgeBuilder4;
        
        internal static global::net.sf.jni4net.jni.MethodId _newKnowledgeBuilder5;
        
        internal static global::net.sf.jni4net.jni.MethodId _newKnowledgeBuilder6;
        
        internal static global::net.sf.jni4net.jni.MethodId _newJaxbConfiguration7;
        
        private @__KnowledgeBuilderFactoryService(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass = @__class;
            global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilderConfiguration0 = @__env.GetMethodID(global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass, "newKnowledgeBuilderConfiguration", "(Ljava/util/Properties;[Ljava/lang/ClassLoader;)Lorg/drools/builder/KnowledgeBuil" +
                    "derConfiguration;");
            global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilderConfiguration1 = @__env.GetMethodID(global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass, "newKnowledgeBuilderConfiguration", "()Lorg/drools/builder/KnowledgeBuilderConfiguration;");
            global::org.drools.builder.@__KnowledgeBuilderFactoryService._newDecisionTableConfiguration2 = @__env.GetMethodID(global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass, "newDecisionTableConfiguration", "()Lorg/drools/builder/DecisionTableConfiguration;");
            global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilder3 = @__env.GetMethodID(global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass, "newKnowledgeBuilder", "(Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lorg/drools/builder/Knowledge" +
                    "Builder;");
            global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilder4 = @__env.GetMethodID(global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass, "newKnowledgeBuilder", "(Lorg/drools/KnowledgeBase;)Lorg/drools/builder/KnowledgeBuilder;");
            global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilder5 = @__env.GetMethodID(global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass, "newKnowledgeBuilder", "(Lorg/drools/KnowledgeBase;Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lor" +
                    "g/drools/builder/KnowledgeBuilder;");
            global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilder6 = @__env.GetMethodID(global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass, "newKnowledgeBuilder", "()Lorg/drools/builder/KnowledgeBuilder;");
            global::org.drools.builder.@__KnowledgeBuilderFactoryService._newJaxbConfiguration7 = @__env.GetMethodID(global::org.drools.builder.@__KnowledgeBuilderFactoryService.staticClass, "newJaxbConfiguration", "(Lcom/sun/tools/xjc/Options;Ljava/lang/String;)Lorg/drools/builder/JaxbConfigurat" +
                    "ion;");
        }
        
        public global::org.drools.builder.KnowledgeBuilderConfiguration newKnowledgeBuilderConfiguration(global::java.util.Properties par0, java.lang.ClassLoader[] par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderConfiguration>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilderConfiguration0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1)));
            }
        }
        
        public global::org.drools.builder.KnowledgeBuilderConfiguration newKnowledgeBuilderConfiguration() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderConfiguration>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilderConfiguration1));
            }
        }
        
        public global::org.drools.builder.DecisionTableConfiguration newDecisionTableConfiguration() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.DecisionTableConfiguration>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.@__KnowledgeBuilderFactoryService._newDecisionTableConfiguration2));
            }
        }
        
        public global::org.drools.builder.KnowledgeBuilder newKnowledgeBuilder(global::org.drools.builder.KnowledgeBuilderConfiguration par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilder>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilder3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.builder.KnowledgeBuilderConfiguration>(@__env, par0)));
            }
        }
        
        public global::org.drools.builder.KnowledgeBuilder newKnowledgeBuilder(global::org.drools.KnowledgeBase par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilder>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilder4, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.KnowledgeBase>(@__env, par0)));
            }
        }
        
        public global::org.drools.builder.KnowledgeBuilder newKnowledgeBuilder(global::org.drools.KnowledgeBase par0, global::org.drools.builder.KnowledgeBuilderConfiguration par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilder>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilder5, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.KnowledgeBase>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.builder.KnowledgeBuilderConfiguration>(@__env, par1)));
            }
        }
        
        public global::org.drools.builder.KnowledgeBuilder newKnowledgeBuilder() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilder>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.@__KnowledgeBuilderFactoryService._newKnowledgeBuilder6));
            }
        }
        
        public global::org.drools.builder.JaxbConfiguration newJaxbConfiguration(global::java.lang.Object par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.JaxbConfiguration>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.@__KnowledgeBuilderFactoryService._newJaxbConfiguration7, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__KnowledgeBuilderFactoryService);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "newKnowledgeBuilderConfiguration", "newKnowledgeBuilderConfiguration0", "(Ljava/util/Properties;[Ljava/lang/ClassLoader;)Lorg/drools/builder/KnowledgeBuil" +
                        "derConfiguration;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "newKnowledgeBuilderConfiguration", "newKnowledgeBuilderConfiguration1", "()Lorg/drools/builder/KnowledgeBuilderConfiguration;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "newDecisionTableConfiguration", "newDecisionTableConfiguration2", "()Lorg/drools/builder/DecisionTableConfiguration;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "newKnowledgeBuilder", "newKnowledgeBuilder3", "(Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lorg/drools/builder/Knowledge" +
                        "Builder;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "newKnowledgeBuilder", "newKnowledgeBuilder4", "(Lorg/drools/KnowledgeBase;)Lorg/drools/builder/KnowledgeBuilder;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "newKnowledgeBuilder", "newKnowledgeBuilder5", "(Lorg/drools/KnowledgeBase;Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lor" +
                        "g/drools/builder/KnowledgeBuilder;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "newKnowledgeBuilder", "newKnowledgeBuilder6", "()Lorg/drools/builder/KnowledgeBuilder;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "newJaxbConfiguration", "newJaxbConfiguration7", "(Lcom/sun/tools/xjc/Options;Ljava/lang/String;)Lorg/drools/builder/JaxbConfigurat" +
                        "ion;"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle newKnowledgeBuilderConfiguration0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Ljava/util/Properties;[Ljava/lang/ClassLoader;)Lorg/drools/builder/KnowledgeBuilderConfiguration;
            // (Ljava/util/Properties;[Ljava/lang/ClassLoader;)Lorg/drools/builder/KnowledgeBuilderConfiguration;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.KnowledgeBuilderFactoryService @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderFactoryService>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.KnowledgeBuilderConfiguration>(@__env, @__real.newKnowledgeBuilderConfiguration(global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.util.Properties>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2Cp<java.lang.ClassLoader[], global::java.lang.ClassLoader>(@__env, par1)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle newKnowledgeBuilderConfiguration1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lorg/drools/builder/KnowledgeBuilderConfiguration;
            // ()Lorg/drools/builder/KnowledgeBuilderConfiguration;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.KnowledgeBuilderFactoryService @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderFactoryService>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.KnowledgeBuilderConfiguration>(@__env, @__real.newKnowledgeBuilderConfiguration());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle newDecisionTableConfiguration2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lorg/drools/builder/DecisionTableConfiguration;
            // ()Lorg/drools/builder/DecisionTableConfiguration;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.KnowledgeBuilderFactoryService @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderFactoryService>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.DecisionTableConfiguration>(@__env, @__real.newDecisionTableConfiguration());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle newKnowledgeBuilder3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lorg/drools/builder/KnowledgeBuilder;
            // (Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lorg/drools/builder/KnowledgeBuilder;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.KnowledgeBuilderFactoryService @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderFactoryService>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.KnowledgeBuilder>(@__env, @__real.newKnowledgeBuilder(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderConfiguration>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle newKnowledgeBuilder4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Lorg/drools/KnowledgeBase;)Lorg/drools/builder/KnowledgeBuilder;
            // (Lorg/drools/KnowledgeBase;)Lorg/drools/builder/KnowledgeBuilder;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.KnowledgeBuilderFactoryService @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderFactoryService>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.KnowledgeBuilder>(@__env, @__real.newKnowledgeBuilder(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.KnowledgeBase>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle newKnowledgeBuilder5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Lorg/drools/KnowledgeBase;Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lorg/drools/builder/KnowledgeBuilder;
            // (Lorg/drools/KnowledgeBase;Lorg/drools/builder/KnowledgeBuilderConfiguration;)Lorg/drools/builder/KnowledgeBuilder;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.KnowledgeBuilderFactoryService @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderFactoryService>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.KnowledgeBuilder>(@__env, @__real.newKnowledgeBuilder(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.KnowledgeBase>(@__env, par0), global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderConfiguration>(@__env, par1)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle newKnowledgeBuilder6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lorg/drools/builder/KnowledgeBuilder;
            // ()Lorg/drools/builder/KnowledgeBuilder;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.KnowledgeBuilderFactoryService @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderFactoryService>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.KnowledgeBuilder>(@__env, @__real.newKnowledgeBuilder());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle newJaxbConfiguration7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Lcom/sun/tools/xjc/Options;Ljava/lang/String;)Lorg/drools/builder/JaxbConfiguration;
            // (Ljava/lang/Object;Ljava/lang/String;)Lorg/drools/builder/JaxbConfiguration;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.KnowledgeBuilderFactoryService @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.KnowledgeBuilderFactoryService>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.JaxbConfiguration>(@__env, @__real.newJaxbConfiguration(global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par1)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.builder.@__KnowledgeBuilderFactoryService(@__env);
            }
        }
    }
    #endregion
}
