//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.@event.process {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class DefaultProcessEventListener : global::java.lang.Object, global::org.drools.@event.process.ProcessEventListener {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeProcessStarted0;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterProcessStarted1;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeProcessCompleted2;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterProcessCompleted3;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeNodeTriggered4;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterNodeTriggered5;
        
        internal static global::net.sf.jni4net.jni.MethodId _beforeNodeLeft6;
        
        internal static global::net.sf.jni4net.jni.MethodId _afterNodeLeft7;
        
        internal static global::net.sf.jni4net.jni.MethodId @__ctorDefaultProcessEventListener8;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public DefaultProcessEventListener() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, global::org.drools.@event.process.DefaultProcessEventListener.@__ctorDefaultProcessEventListener8, this);
            }
        }
        
        protected DefaultProcessEventListener(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.@event.process.DefaultProcessEventListener.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.@event.process.DefaultProcessEventListener.staticClass = @__class;
            global::org.drools.@event.process.DefaultProcessEventListener._beforeProcessStarted0 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "beforeProcessStarted", "(Lorg/drools/event/process/ProcessStartedEvent;)V");
            global::org.drools.@event.process.DefaultProcessEventListener._afterProcessStarted1 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "afterProcessStarted", "(Lorg/drools/event/process/ProcessStartedEvent;)V");
            global::org.drools.@event.process.DefaultProcessEventListener._beforeProcessCompleted2 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "beforeProcessCompleted", "(Lorg/drools/event/process/ProcessCompletedEvent;)V");
            global::org.drools.@event.process.DefaultProcessEventListener._afterProcessCompleted3 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "afterProcessCompleted", "(Lorg/drools/event/process/ProcessCompletedEvent;)V");
            global::org.drools.@event.process.DefaultProcessEventListener._beforeNodeTriggered4 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "beforeNodeTriggered", "(Lorg/drools/event/process/ProcessNodeTriggeredEvent;)V");
            global::org.drools.@event.process.DefaultProcessEventListener._afterNodeTriggered5 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "afterNodeTriggered", "(Lorg/drools/event/process/ProcessNodeTriggeredEvent;)V");
            global::org.drools.@event.process.DefaultProcessEventListener._beforeNodeLeft6 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "beforeNodeLeft", "(Lorg/drools/event/process/ProcessNodeLeftEvent;)V");
            global::org.drools.@event.process.DefaultProcessEventListener._afterNodeLeft7 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "afterNodeLeft", "(Lorg/drools/event/process/ProcessNodeLeftEvent;)V");
            global::org.drools.@event.process.DefaultProcessEventListener.@__ctorDefaultProcessEventListener8 = @__env.GetMethodID(global::org.drools.@event.process.DefaultProcessEventListener.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/process/ProcessStartedEvent;)V")]
        public virtual void beforeProcessStarted(global::org.drools.@event.process.ProcessStartedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.process.DefaultProcessEventListener._beforeProcessStarted0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.process.ProcessStartedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/process/ProcessStartedEvent;)V")]
        public virtual void afterProcessStarted(global::org.drools.@event.process.ProcessStartedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.process.DefaultProcessEventListener._afterProcessStarted1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.process.ProcessStartedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/process/ProcessCompletedEvent;)V")]
        public virtual void beforeProcessCompleted(global::org.drools.@event.process.ProcessCompletedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.process.DefaultProcessEventListener._beforeProcessCompleted2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.process.ProcessCompletedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/process/ProcessCompletedEvent;)V")]
        public virtual void afterProcessCompleted(global::org.drools.@event.process.ProcessCompletedEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.process.DefaultProcessEventListener._afterProcessCompleted3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.process.ProcessCompletedEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/process/ProcessNodeTriggeredEvent;)V")]
        public virtual void beforeNodeTriggered(global::org.drools.@event.process.ProcessNodeTriggeredEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.process.DefaultProcessEventListener._beforeNodeTriggered4, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.process.ProcessNodeTriggeredEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/process/ProcessNodeTriggeredEvent;)V")]
        public virtual void afterNodeTriggered(global::org.drools.@event.process.ProcessNodeTriggeredEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.process.DefaultProcessEventListener._afterNodeTriggered5, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.process.ProcessNodeTriggeredEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/process/ProcessNodeLeftEvent;)V")]
        public virtual void beforeNodeLeft(global::org.drools.@event.process.ProcessNodeLeftEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.process.DefaultProcessEventListener._beforeNodeLeft6, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.process.ProcessNodeLeftEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/event/process/ProcessNodeLeftEvent;)V")]
        public virtual void afterNodeLeft(global::org.drools.@event.process.ProcessNodeLeftEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.@event.process.DefaultProcessEventListener._afterNodeLeft7, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.@event.process.ProcessNodeLeftEvent>(@__env, par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.@event.process.DefaultProcessEventListener(@__env);
            }
        }
    }
    #endregion
}
