// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.drools.definition.process;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class Node_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return org.drools.definition.process.Node_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        org.drools.definition.process.Node_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __Node extends system.Object implements org.drools.definition.process.Node {
    
    protected __Node(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getName();
    
    @net.sf.jni4net.attributes.ClrMethod("()J")
    public native long getId();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Map;")
    public native java.util.Map getMetaData();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native java.lang.Object getMetaData(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List getIncomingConnections(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Map;")
    public native java.util.Map getIncomingConnections();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List getOutgoingConnections(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/util/Map;")
    public native java.util.Map getOutgoingConnections();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lorg/drools/definition/process/NodeContainer;")
    public native org.drools.definition.process.NodeContainer getNodeContainer();
}
//</generated-proxy>
