//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.builder.conf {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface KnowledgeBuilderOptionsConfiguration {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/drools/builder/conf/KnowledgeBuilderOption;)V")]
        void setOption(global::org.drools.builder.conf.KnowledgeBuilderOption par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Class;Ljava/lang/String;)Lorg/drools/builder/conf/MultiValueKnowledge" +
            "BuilderOption;")]
        global::org.drools.builder.conf.MultiValueKnowledgeBuilderOption getOption(global::java.lang.Class par0, global::java.lang.String par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Class;)Lorg/drools/builder/conf/SingleValueKnowledgeBuilderOption;")]
        global::org.drools.builder.conf.SingleValueKnowledgeBuilderOption getOption(global::java.lang.Class par0);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class KnowledgeBuilderOptionsConfiguration_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration), typeof(global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration), typeof(global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration_))]
    internal sealed partial class @__KnowledgeBuilderOptionsConfiguration : global::java.lang.Object, global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _setOption0;
        
        internal static global::net.sf.jni4net.jni.MethodId _getOption1;
        
        internal static global::net.sf.jni4net.jni.MethodId _getOption2;
        
        private @__KnowledgeBuilderOptionsConfiguration(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration.staticClass = @__class;
            global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration._setOption0 = @__env.GetMethodID(global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration.staticClass, "setOption", "(Lorg/drools/builder/conf/KnowledgeBuilderOption;)V");
            global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration._getOption1 = @__env.GetMethodID(global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration.staticClass, "getOption", "(Ljava/lang/Class;Ljava/lang/String;)Lorg/drools/builder/conf/MultiValueKnowledge" +
                    "BuilderOption;");
            global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration._getOption2 = @__env.GetMethodID(global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration.staticClass, "getOption", "(Ljava/lang/Class;)Lorg/drools/builder/conf/SingleValueKnowledgeBuilderOption;");
        }
        
        public void setOption(global::org.drools.builder.conf.KnowledgeBuilderOption par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration._setOption0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::org.drools.builder.conf.KnowledgeBuilderOption>(@__env, par0));
            }
        }
        
        public global::org.drools.builder.conf.MultiValueKnowledgeBuilderOption getOption(global::java.lang.Class par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.conf.MultiValueKnowledgeBuilderOption>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration._getOption1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        public global::org.drools.builder.conf.SingleValueKnowledgeBuilderOption getOption(global::java.lang.Class par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.conf.SingleValueKnowledgeBuilderOption>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration._getOption2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__KnowledgeBuilderOptionsConfiguration);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setOption", "setOption0", "(Lorg/drools/builder/conf/KnowledgeBuilderOption;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getOption", "getOption1", "(Ljava/lang/Class;Ljava/lang/String;)Lorg/drools/builder/conf/MultiValueKnowledge" +
                        "BuilderOption;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getOption", "getOption2", "(Ljava/lang/Class;)Lorg/drools/builder/conf/SingleValueKnowledgeBuilderOption;"));
            return methods;
        }
        
        private static void setOption0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Lorg/drools/builder/conf/KnowledgeBuilderOption;)V
            // (Lorg/drools/builder/conf/KnowledgeBuilderOption;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration>(@__env, @__obj);
            @__real.setOption(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.conf.KnowledgeBuilderOption>(@__env, par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getOption1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Ljava/lang/Class;Ljava/lang/String;)Lorg/drools/builder/conf/MultiValueKnowledgeBuilderOption;
            // (Ljava/lang/Class;Ljava/lang/String;)Lorg/drools/builder/conf/MultiValueKnowledgeBuilderOption;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.conf.MultiValueKnowledgeBuilderOption>(@__env, @__real.getOption(global::net.sf.jni4net.utils.Convertor.StrongJ2CpClass(@__env, par0), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par1)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getOption2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/Class;)Lorg/drools/builder/conf/SingleValueKnowledgeBuilderOption;
            // (Ljava/lang/Class;)Lorg/drools/builder/conf/SingleValueKnowledgeBuilderOption;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.builder.conf.KnowledgeBuilderOptionsConfiguration>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.builder.conf.SingleValueKnowledgeBuilderOption>(@__env, @__real.getOption(global::net.sf.jni4net.utils.Convertor.StrongJ2CpClass(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.builder.conf.@__KnowledgeBuilderOptionsConfiguration(@__env);
            }
        }
    }
    #endregion
}
