//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.drools.runtime.rule {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface Activation {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/definition/rule/Rule;")]
        global::org.drools.definition.rule.Rule getRule();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/List;")]
        global::java.util.List getObjects();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/List;")]
        global::java.util.List getFactHandles();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/drools/runtime/rule/PropagationContext;")]
        global::org.drools.runtime.rule.PropagationContext getPropagationContext();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/List;")]
        global::java.util.List getDeclarationIDs();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/lang/Object;")]
        global::java.lang.Object getDeclarationValue(global::java.lang.String par0);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class Activation_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::org.drools.runtime.rule.@__Activation.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::org.drools.runtime.rule.Activation), typeof(global::org.drools.runtime.rule.Activation_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::org.drools.runtime.rule.Activation), typeof(global::org.drools.runtime.rule.Activation_))]
    internal sealed partial class @__Activation : global::java.lang.Object, global::org.drools.runtime.rule.Activation {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId _getRule0;
        
        internal static global::net.sf.jni4net.jni.MethodId _getObjects1;
        
        internal static global::net.sf.jni4net.jni.MethodId _getFactHandles2;
        
        internal static global::net.sf.jni4net.jni.MethodId _getPropagationContext3;
        
        internal static global::net.sf.jni4net.jni.MethodId _getDeclarationIDs4;
        
        internal static global::net.sf.jni4net.jni.MethodId _getDeclarationValue5;
        
        private @__Activation(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::org.drools.runtime.rule.@__Activation.staticClass = @__class;
            global::org.drools.runtime.rule.@__Activation._getRule0 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Activation.staticClass, "getRule", "()Lorg/drools/definition/rule/Rule;");
            global::org.drools.runtime.rule.@__Activation._getObjects1 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Activation.staticClass, "getObjects", "()Ljava/util/List;");
            global::org.drools.runtime.rule.@__Activation._getFactHandles2 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Activation.staticClass, "getFactHandles", "()Ljava/util/List;");
            global::org.drools.runtime.rule.@__Activation._getPropagationContext3 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Activation.staticClass, "getPropagationContext", "()Lorg/drools/runtime/rule/PropagationContext;");
            global::org.drools.runtime.rule.@__Activation._getDeclarationIDs4 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Activation.staticClass, "getDeclarationIDs", "()Ljava/util/List;");
            global::org.drools.runtime.rule.@__Activation._getDeclarationValue5 = @__env.GetMethodID(global::org.drools.runtime.rule.@__Activation.staticClass, "getDeclarationValue", "(Ljava/lang/String;)Ljava/lang/Object;");
        }
        
        public global::org.drools.definition.rule.Rule getRule() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.definition.rule.Rule>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Activation._getRule0));
            }
        }
        
        public global::java.util.List getObjects() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Activation._getObjects1));
            }
        }
        
        public global::java.util.List getFactHandles() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Activation._getFactHandles2));
            }
        }
        
        public global::org.drools.runtime.rule.PropagationContext getPropagationContext() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.PropagationContext>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Activation._getPropagationContext3));
            }
        }
        
        public global::java.util.List getDeclarationIDs() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Activation._getDeclarationIDs4));
            }
        }
        
        public global::java.lang.Object getDeclarationValue(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::org.drools.runtime.rule.@__Activation._getDeclarationValue5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Activation);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getRule", "getRule0", "()Lorg/drools/definition/rule/Rule;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getObjects", "getObjects1", "()Ljava/util/List;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFactHandles", "getFactHandles2", "()Ljava/util/List;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getPropagationContext", "getPropagationContext3", "()Lorg/drools/runtime/rule/PropagationContext;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDeclarationIDs", "getDeclarationIDs4", "()Ljava/util/List;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDeclarationValue", "getDeclarationValue5", "(Ljava/lang/String;)Ljava/lang/Object;"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getRule0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lorg/drools/definition/rule/Rule;
            // ()Lorg/drools/definition/rule/Rule;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Activation @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Activation>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.definition.rule.Rule>(@__env, @__real.getRule());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getObjects1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/List;
            // ()Ljava/util/List;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Activation @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Activation>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.List>(@__env, @__real.getObjects());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getFactHandles2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/List;
            // ()Ljava/util/List;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Activation @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Activation>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.List>(@__env, @__real.getFactHandles());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getPropagationContext3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lorg/drools/runtime/rule/PropagationContext;
            // ()Lorg/drools/runtime/rule/PropagationContext;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Activation @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Activation>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::org.drools.runtime.rule.PropagationContext>(@__env, @__real.getPropagationContext());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getDeclarationIDs4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/util/List;
            // ()Ljava/util/List;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Activation @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Activation>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.util.List>(@__env, @__real.getDeclarationIDs());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getDeclarationValue5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Ljava/lang/Object;
            // (Ljava/lang/String;)Ljava/lang/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::org.drools.runtime.rule.Activation @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::org.drools.runtime.rule.Activation>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.lang.Object>(@__env, @__real.getDeclarationValue(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::org.drools.runtime.rule.@__Activation(@__env);
            }
        }
    }
    #endregion
}
